feat: sync team_components table with the deletion of components & teams
flanksource/duty pull request #250
Opened 2023-08-14 10:55 UTC by adityathebe

Resolves: https://github.com/flanksource/incident-commander/issues/408

2023-08-14 11:41 UTC, yashmehrotra commented on views/007_events.sql
> +  END IF;
Can we also do deletions for component relationships and other related resources as well ?

2023-08-14 11:42 UTC, yashmehrotra commented on views/007_events.sql
> +  END IF;
Also, I think these should be in a different file ? Like how we created a new one for canaries/check deletion handling

Doesn't belong in events.sql

2023-08-15 05:27 UTC, yashmehrotra approved these changes
:shipit:

2023-08-15 13:35 UTC, moshloop commented on views/018_component_triggers.sql
> +    DELETE FROM team_components WHERE component_id = OLD.id;
I am not sure we should be doing this - If I am looking at a deleted component, I still want to see what it was related to before it was deleted. 

A relationship should only be deleted when it is no longer true e.g. An EBS volume is detached from an ec2instance - in which case the component/config relationship.deleted_at should reflect the detach time

2023-08-15 13:36 UTC, moshloop commented on views/019_teams_triggers.sql
> +    DELETE FROM team_components WHERE team_id = OLD.id;
This is ok, when deleting a team they no longer "own" any components.

2023-08-21 09:36 UTC, moshloop requested changes

2023-08-21 09:36 UTC, moshloop commented on views/018_component_triggers.sql
> +    DELETE FROM team_components WHERE component_id = OLD.id;
@adityathebe  / @yashmehrotra  ^

2023-08-25 08:36 UTC, moshloop approved these changes

2023-08-25 08:41 UTC, merged